# This workflows will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  pull_request:
    types:
    - opened
    - reopened
    - labeled
    branches:
    - 'release/**'
    - 'main'
    - develop
  push:
    branches:
      - 'main'
      - develop
jobs:
  build:
    if: |
      contains(github.event.pull_request.labels.*.name, 'run tests') || 
      contains(fromJSON('["develop", "main"]'), github.ref_name) || 
      (github.event_name == 'pull_request' && github.event.action == 'opened')
      

    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Lint with flake8
      run: |
        poetry run flake8 .
    
    - name: Build and run postgres containers
      run: |
        docker-compose build

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yaml" down
    