version: "3.8"

volumes:
  fast-api-db:

services:
  api:
    build:
      context: .
    command: ["sh", "-c", "bash prestart.sh && python main.py"]
    ports:
      - "8080:8080"
    volumes:
    - ./:/app/code/
    env_file:
      - 'src/environments/development.env'
    environment:
      - DATABASE_HOSTNAME=simplenight-api-db
    depends_on:
      - simplenight-api-db

  simplenight-api-db:
    image: postgres:13
    volumes:
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
      - fast-api-db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: simplenight
