# This workflows will install Python dependencies and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Tests

on:
  pull_request:
    types:
    - opened
    - reopened
    - labeled
    branches:
    - 'release/**'
    - 'main'
    - develop
  push:
    branches:
      - 'main'
      - develop


jobs:
  build:
    if: |
      contains(github.event.pull_request.labels.*.name, 'run tests') || 
      contains(fromJSON('["develop", "main"]'), github.ref_name) || 
      (github.event_name == 'pull_request' && github.event.action == 'opened')

    runs-on: ubuntu-latest

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Set up Python environment using poetry
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Poetry Install
      uses: knowsuchagency/poetry-install@v2
      with:
        create-virtualenv: true

    - name: Install dependencies with poetry
      run: |
        poetry install

    - name: Build and run all containers
      run: |
        docker-compose build
        docker-compose up -d

    - name: Run tests
      run: pytest

    - name: Stop containers
      if: always()
      run: docker-compose stop
